### ISSUE TITLE
How to download the video

### ISSUE THREAD

**Issue by RachelLYY** [tanqiu98/2G-GCN#2]
Hi, I've already downloaded the google drive 3 zip files but found out that there's no videos, only annotations. May I know how to download the videos? Thanks a lot!

**Comment by tanqiu98** [comment]
Hi,

You can find all raw data (including RGB frames of videos) via the link in the "MPHOI-72 RGB-D dataset" section. If you still need the video, I'm glad to discuss sharing with you through email.

Kind regards,
Tanqiu

**Comment by RachelLYY** [comment]
> 

Hi, I've opened it but didn't find the download link. Are only users of that web can download it? If so, I also didn't find the sign-up link, maybe only students at Durham University can have an account and then download the dataset? Thanks.

**Comment by tanqiu98** [comment]
Hi,

Sorry for the inconvenience. The server collapses occasionally, but it looks okay now, I think? Please check that.

Cheers,
Tanqiu

**Comment by RachelLYY** [comment]
> Hi,
> 
> Sorry for the inconvenience. The server collapses occasionally, but it looks okay now, I think? Please check that.
> 
> Cheers, Tanqiu

It's ok now! Thanks!
