### ISSUE TITLE
Data download(RGB and Depth)

### ISSUE THREAD

**Issue by ga94zot** [tanqiu98/2G-GCN#3]
Dear Tanqiu,

Is there any method to download your rgb+depth data faster?

I found it a little bit hard for me to download them.

Thank you in advance!

Best regards,
Yuankai

**Comment by tanqiu98** [comment]
Hi Yuankai,

We've added a new OneDrive link to help you download datasets more convenient. Please check that when you have time.

Cheers,
Tanqiu

**Comment by ga94zot** [comment]
Hi Tanqiu,

Thanks for your reply and it works pretty good! 

Thank you very much for the help and hope you have a nice day!

Best regards,
Yuankai

**Comment by linjing7** [comment]
@ga94zot Have you downloaded the RGB images and videos? The original one-drop link is not available now. Could you please share your dataset with me?
